services:
  mock-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: mkaganm/mock-api:latest
    container_name: mock-api
    restart: always
    environment:
      PORT: "8081"
    ports:
      - "8081:8081"