services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    environment:
      # Your API base URL if needed by tests
      - PLAYWRIGHT_BASE_URL=http://host.docker.internal:8081
      # Where Playwright Allure reporter will write raw results
      - ALLURE_RESULTS_DIR=/app/allure-results
    volumes:
      # Bind mounts so results & report are written to the Jenkins workspace
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
      - ./playwright-report:/app/playwright-report
    command: >
      sh -lc "
        echo 'Running tests...' &&
        npm run test:api || true &&
        echo 'Generating Allure report inside container...' &&
        npx allure generate --clean --output ./allure-report ./allure-results || true &&
        echo 'Done.'
      "

  # Optional live Allure service (not required for Jenkins publishHTML)
  allure-server:
    image: frankescobar/allure-docker-service
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=1
      - KEEP_HISTORY=1
