version: "3.9"
services:
  # Test runner service
  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    environment:
      - PLAYWRIGHT_BASE_URL=http://host.docker.internal:8081
    depends_on: []
    volumes:
      - ./allure-report:/app/allure-report
      - ./allure-results:/app/allure-results
      - ./playwright-report:/app/playwright-report
    command: >
      sh -c "
        echo 'Running tests...' &&
        npm run test:api &&
        echo 'Generating Allure report...' &&
        npx allure generate --clean &&
        echo 'Tests completed!'
      "

  # Allure report server
  allure-server:
    image: frankescobar/allure-docker-service
    ports:
      - "5050:5050"
    volumes:
      - ./allure-report:/app/allure-results
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=1
      - KEEP_HISTORY=1
    depends_on:
      - tests
