version: '3.8'

services:
  playwright-tests:
    build: .
    volumes:
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report
    environment:
      - CI=true
    command: npx playwright test
